### ISSUE TITLE
QML: second video in playlist is stretched to the size of first played

### ISSUE THREAD

**Issue by alanvice** [carlonluca/pi#41] opened 2015-10-15 14:59 UTC
First video 1920x1080, second video 1920x768
The second video is played in the viewport size of the first one when fillMode: Image.PreserveAspectFit is selected.

**Comment by atr0n** [comment] 2015-10-19 22:32
Try it with fillMode:VideoOutput.PreserveAspectFit. It seems you use the Image version.

**Comment by alanvice** [comment] 2015-10-20 07:22
just tried it , same behavior.

I forgot to say I'm using the v5.0.0 tag.
As you can see it's the same value:
console.log("VideoOutput.PreserveAspectFit",VideoOutput.PreserveAspectFit);
console.log("Image.PreserveAspectFit",Image.PreserveAspectFit);
Output:
qml: VideoOutput.PreserveAspectFit 1
qml: Image.PreserveAspectFit 1

This is a really bad workaround I tried but seems it hangs after a few hours of running.
Main.qml:
import QtQuick 2.0
import QtMultimedia 5.0

Rectangle {
    id: root
    width: 1920
    height: 1080
    color: "black"
    property var object

    property int index:0
    property string folder: "/folder/to/videos/"
	property var playlist: [
		"Video1.mp4",
		"Video2.mp4",
		"Video3.mp4"
	];

    function startVideo(sourceFile)
    {
        var component = Qt.createComponent("Video.qml");
        if(component.status == Component.Ready)
        {
            object = component.createObject(root);
            object.fillMode=VideoOutput.PreserveAspectFit
            object.anchors.fill=root
            object.autoPlay=true
            object.source=folder+sourceFile
            object.onRealStopped.connect(nextVideo)
        }
    }

    function nextVideo()
    {
        object.destroy();
        index++
        if(index>=playlist.length)
             index=0
	startVideo(playlist[index])
    }

    Component.onCompleted: {
	startVideo(playlist[index])
    }
}

Video.qml:
import QtQuick 2.0
import QtMultimedia 5.0

Video {
// signal realStopped is necessary to skip the initial State changing from 
// STATE_INACTIVE to STATE_STOPPED...
    signal realStopped
    property bool hasPlayed: false
    onStatusChanged: {
        if(status == MediaPlayer.EndOfMedia) 
            hasPlayed = true;
    }
    onStopped: { if(hasPlayed) realStopped(); }
}

**Comment by atr0n** [comment] 2015-10-20 07:31
From my experience from other project, it's a good practice add at least one dimension to the videouput. For this propose, you can use meted information.
The following code was used on one of my project:
```
Video{
       source: base.source;
        onStatusChanged: {
            if(status === MediaPlayer.Loaded){
                // If not recognized, use fullscreen
                if(metaData.resolution === undefined) loaded(1920,1080);
                // else, use native
                else loaded(metaData.resolution.width,metaData.resolution.height);
            }
        }
    }
```

**Comment by alanvice** [comment] 2015-10-20 07:36
I set the Video component dimensions with:
object.anchors.fill=root
so it takes the root dimensions, and shows correctly on screen

**Comment by atr0n** [comment] 2015-10-20 15:13
If you use anchor.fill you are going to get always fullscreen size. Use metadata or fixed value.
Metadata.resolution will always be found as long as you wait the content to be loaded and be referenced to a Video/Image object.
Anyway, I do not thing these is a problem related PiOmxTexture.
Did you make your code work on windows?

**Comment by alanvice** [comment] 2015-10-20 18:15
My project works well on windows and linux, even on arm utilite, now i'm trying to make it work on Raspberry.
Your project is fantastic but if you try to play different resolution videos with the flag fillMode:VideoOutput.PreserveAspectFit to keep the right aspect, the viewport will remain the size of the first ever video played. Obviously you don't have to close the program.

Try this over a raspberry in egl platform (not xcb):
Start your POC player, select a 4/3 aspect ratio video. On a 16/9 screen the video will be resized the right way leaving 2 bands on the sides. Now stop it without closing the player and open a 16/9 video. The second video (that should be played fullscreen) will be played in the viewport of the first one.
If you invert the order you will see the 16/9 video well displayed, then the 4/3 video stretched to fullscreen.

I'm saying it is a problem in libs, maybe in OMXVideo.cpp, where it should change the viewport dimensions/ratio.

**Comment by atr0n** [comment] 2015-10-20 18:36
Ok, my bad.
The code I posted do not work(at least that's what I guess after a quick review) because "resolution" in not into OMX_MetaDataProvider::onUpdateRequested function.
Could you try something? Try to anchor your "object" item as centerIn: parent. Then, manually insert 1920x1080 at the first video and  1920x768 at the second.
Let's see if at least this work manually.

**Comment by alanvice** [comment] 2015-10-21 08:12
OK, I will try to manually insert dimensions...
Now i have taken some screenshots from my raspberry using pocplayer:
First execution, first video 1920x768, second video 1920x1080
![video1-first](https://cloud.githubusercontent.com/assets/9517255/10631036/6587579a-77db-11e5-8cbd-bc9af00a6d53.png)
![video2-second](https://cloud.githubusercontent.com/assets/9517255/10631035/6585ac1a-77db-11e5-9a4a-2fc55accbf8f.png)
As you can see the second video (FullHD) should be fullscreen instead it is in the size of the first one.

Now trying the reverse order, first video 1920x1080, second video 1920x768:
![video2-first](https://cloud.githubusercontent.com/assets/9517255/10631106/e9032856-77db-11e5-96f9-865e1da60411.jpg)
![video1-second](https://cloud.githubusercontent.com/assets/9517255/10631108/ecd11876-77db-11e5-8916-4b568357ae89.png)
Now the problem is that the smaller video played as second is stretched to the size of the first one.

Meanwhile i found another bug, the first video is player ok, the second,third etc... video will start playing at 10 seconds +- (I will investigate today if I can).

**Comment by alanvice** [comment] 2015-10-21 10:11
I've done the test resizing the Video component manually to the video native size.
All video tested are mp4/h264-aac. 
Don't look at the DIVX logo because I re-encoded all the videos.

Code used:
    import QtQuick 2.0
    import QtMultimedia 5.0
    
    Rectangle {
        id: root
        width: 1920
        height: 1080
        color: "black"
        property var object
    
        property int index:0
        property string prefix: "/folder/to/videos/"
        property var playlist: [
    //    prefix + "Video1920x1080.mp4",
        prefix + "Video1920x768.mp4",
        prefix + "Video1920x1080.mp4"
        ];
        property var dimensions: [
    //            [1920,1080],
                [1920,768],
                [1920,1080]
        ];
    
        function nextVideo()
        {
            index++;
            if(index>=playlist.length)
                 index=0;
    
            video.source=playlist[index];
            console.log("Setting size:",dimensions[index]);
            video.width=dimensions[index][0]
            video.height=dimensions[index][1]
            video.play();
        }
    
        Video {
            id: video
            //anchors.fill: parent
            anchors.centerIn: parent
            autoPlay: false //true
            fillMode: VideoOutput.PreserveAspectFit
            onStopped: nextVideo();
        }
    
        Component.onCompleted: {
            video.source=playlist[index];
            console.log("Setting size:",dimensions[index]);
            video.width=dimensions[index][0]
            video.height=dimensions[index][1]
            video.play();
        }
    }
    
First execution, first video 1920x768, second video 1920x1080:
![bike1](https://cloud.githubusercontent.com/assets/9517255/10633352/64d9fbfe-77ea-11e5-9398-086b07a41041.png)
![forte2](https://cloud.githubusercontent.com/assets/9517255/10633353/64dae758-77ea-11e5-8ea8-4036156cef86.jpg)
The second video is small even if the qml Video component is sized to 1920x1080.

Reverse order, first video 1920x1080, second video 1920x768:
![forte1](https://cloud.githubusercontent.com/assets/9517255/10633400/ae19193a-77ea-11e5-93b0-672156338e97.jpg)
![bike2](https://cloud.githubusercontent.com/assets/9517255/10633402/b184a832-77ea-11e5-8146-b3858326c49a.png)
In this case reducing the height of the second video makes the qml squeeze the video (look the wheels) because it thinks it is still a fullhd video.


Also confirming the second bug: the second video starts from a random time between the 5th and the 11th second even if doing a seek(0) before play(). 
Only doing a play(), stop(), play() ti will start from the beginning of the video.
Hope my tests will help you.

**Comment by carlonluca** [comment] 2015-10-25 13:20
You should find the fix for this in the next release. For the start position issue please file another report with a description on how to reproduce (I tried to reproduce but I failed).

**Closed** 2015-10-25 13:21 UTC
Labels: bug
